apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: uetylsnkj-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/uetylsnkj-java-springboot-gitops